import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Taufiq R | Mobile Portfolio",
  description: "Welcome to my Mobile Developer portfolio showcasing modern mobile apps and projects.",
  keywords: [
    "android",
    "android-developer",
    "kotlin",
    "jetpack-compose",
    "compose",
    "mvvm",
    "clean-architecture",
    "android-jetpack",
    "material-design",
    "mobile-app",
    "mobile-development",
    "native-android",
    "portfolio",
    "developer-portfolio",
    "firebase",
    "room-database",
    "retrofit",
    "coroutines",
    "flow",
    "rest-api",
    "github",
    "git",
    "ui-ux",
    "modern-ui",
    "responsive-design",
    "android-studio",
    "xml",
    "dicoding",
    "software-engineer"
  ] as Array<string>,
  authors: {
    name: "Taufiqur Rohman",
    url: "https://github.com/taufiqurrohman132",
  },
} as const;
